### ISSUE TITLE
Build Type "Release" breaks Greedy Search

### ISSUE THREAD

**Issue by ghost** [ipa320/seneka_deployment_strategies#16]
If you set the build type of seneka_sensor_placement to Release, the greedy search always returns coverage 0!
Temproary fix in c91ca8279f4c3b8d36536fc307e4319ed1dcbbc9

**Comment by mgruhler** [comment]
Actually already starts with optimization -O1.
Does not break PSO or GreedyPSO --> Only related to GreedySearch.

Maybe multithreading/OMPL problem? or Timing issue?
